name = "QuasiMonteCarlo"
uuid = "930ad830-f216-4aea-9ccd-a5929060ab3a"
authors = ["Chad Scherrer"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
